config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  get "ui_pages" => "ui_pages#index"
  get "ui_add_class" => "ui_pages#add_class", :as => :ui_add_class
  get "ui_add_teacher" => "ui_pages#add_teacher", :as => :ui_add_teacher
  get "ui_new_lesson" => "ui_pages#new_lesson", :as => :ui_create_lesson
  get "ui_edit_lesson" => "ui_pages#edit_lesson", :as => :ui_edit_lesson
  get "ui_add_student" => "ui_pages#add_student", :as => :ui_add_student
  get "ui_student_list" => "ui_pages#student_list", :as => :ui_student_index
  get "ui_grade_lesson" => "ui_pages#grade_lesson", :as=> :ui_grade_lesson
  post "lesson/start_lesson" =>"lessons#start_lesson", :as=> :start_lesson

  resources :subjects
  resources :teachers
  resources :lessons
  resources :students 
  resources :classes
  resources :assignment_chapters
  resources :class_rooms
  
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action :set_student
  def index
    @subjects = @student.subjects
    
  end

  def show
    @assignments = Assignment.where(student_id:@student.id, subject_id:params[:id]).order('created_at ASC')
  end

  private

  def set_student
    @student = Student.last
  end

end 

app/views/classes/index.html.haml
.container.top-buffer
  .row
    .col-12
      .card
        .card-body
          %h4.header-title 
            Student Name: 
            =@student.full_name
          %br
          %br
          -@subjects.each do |subject|
            %h5.header-title 
              Class: 
              =subject.name
            %h5.header-title 
              Teacher: 
              =subject.teacher.full_name
              =link_to "View Class Lessons", class_path(subject)
                    

  

app/views/classes/show.html.haml
.container.top-buffer
  .row
    .col-12
      .card
        .card-body
          %h4.header-title 
            Student Name: 
            =@student.full_name
          %br
          %br
          
            
            .table-responsive
              %table.table.mb-0
                %thead
                  %tr
                    %th{:scope => "col"} Lesson
                    %th{:scope => "col"} Section 1
                    %th{:scope => "col"} Section 2
                    %th{:scope => "col"} Section 3
                    %th{:scope => "col"} Section 4
                    %th{:scope => "col"} Section 5
                    
                %tbody
                  -@assignments.each_with_index do |assignment, index|
                    
                    %tr
                      %th{:scope => "row"} 
                        =index + 1
                        %br
                        
                        - if assignment.accessible
                          =link_to "Start Lesson", start_lesson_path(assignment_chapter_id:assignment.assignment_chapters.first.id, subject_id:assignment.subject.id), class: "btn btn-outline-success btn-rounded", method: :post
                      -assignment.assignment_chapters.order('created_at ASC').each do |chapter|
                        %td 
                          =chapter.completed ? "Completed" : "Incomplete"
                          %br
                          - if chapter.accessible
                            =link_to "View", assignment_chapter_path(chapter), class: "btn btn-outline-success btn-rounded"
                          -else
                            Not Yet Available