config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  get "ui_pages" => "ui_pages#index"
  get "ui_add_class" => "ui_pages#add_class", :as => :ui_add_class
  get "ui_add_teacher" => "ui_pages#add_teacher", :as => :ui_add_teacher
  get "ui_new_lesson" => "ui_pages#new_lesson", :as => :ui_create_lesson
  get "ui_edit_lesson" => "ui_pages#edit_lesson", :as => :ui_edit_lesson
  get "ui_add_student" => "ui_pages#add_student", :as => :ui_add_student
  get "ui_student_list" => "ui_pages#student_list", :as => :ui_student_index
  get "ui_grade_lesson" => "ui_pages#grade_lesson", :as=> :ui_grade_lesson
  post "lesson/start_lesson" =>"lessons#start_lesson", :as=> :start_lesson

  resources :subjects
  resources :teachers
  resources :lessons
  resources :students 
  resources :classes
  resources :assignment_chapters
  resources :class_rooms
  
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher
  has_many :lessons
  has_many :enrollments
  has_many :students, through: :enrollments
  has_many :assignments
  validates_presence_of :name, :school_year
end

app/controllers/Subjects_controller.rb
class SubjectsController < ApplicationController 


  def new
    @subject = Subject.new
    @teachers = Teacher.all
  end

  def create
    @subject = Subject.new(subject_params)
    @teachers = Teacher.all
    if @subject.save
      flash[:success] = "You created a new subject."
      redirect_to new_subject_path
    else
      render :new
    end 
  end

  def index
    @subjects = Subject.all
  end

  private

  def subject_params
    params.require(:subject).permit(:name,:teacher_id, :school_year)
  end

end 

app/views/subjects/index.html.haml
.container
  -@subjects.each do |subject|
    %h5
      Class:
      =subject.name.capitalize
    %h5
      Lessons
    %ol
      -subject.lessons.each do |lesson|
        %li
          =link_to "#{lesson.name.capitalize}", edit_lesson_path(lesson)

app/views/subjects/new.html.haml
.container.top-buffer
  .card  
    .card-body
      %h4.mb-3.header-title CREATE CLASS
      .row
      .col-lg-12
        =bootstrap_form_for @subject do |f|
          =f.text_field :name, label:"Subject"
          = f.select :teacher_id, options_for_select(@teachers.collect{ |teacher| [teacher.full_name, teacher.id] }), { label: "Who will teach the class"}
          = f.select :school_year, [["2018/2019", "2018/2019"],["2019/2020", "2019/2020"], ["2020/2021", "2020/2021"]], { label: "Please pick a school year"}
          =f.submit "Create Class", class: "btn btn-primary"